### ISSUE TITLE
Is really pylint in py3 more strict?

### ISSUE THREAD

**Issue by giovannipizzi** [ltalirz/prospector-pylint-absolute-import#3]
I had the same behaviour you describe in the readme, but then I realized I didn't reinstall tzlocal in the new py3 virtualenv... when installing it, I get the same behaviour as in py2. Can you reproduce?

**Comment by ltalirz** [comment]
Indeed!

**Comment by ltalirz** [comment]
So, is the problem that prospector somehow "changes directory" to the file?

**Comment by giovannipizzi** [comment]
Yes! Indeed the problem is with prospector, and apparently they do on purpose! Look what is written in the source code:
https://github.com/PyCQA/prospector/blob/744112f8a837bf48af1f88e66a33e7dfe2368d85/prospector/tools/pylint/__init__.py#L147-L156

**Comment by giovannipizzi** [comment]
I think one should open an issue against prospector

**Comment by ltalirz** [comment]
Agreed, please go ahead

**Comment by giovannipizzi** [comment]
PyCQA/prospector#294
